
import oru.inf.InfDB;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carolinaappel
 */
public class AgentPage extends javax.swing.JFrame {
private InfDB idb;
private String userName;
private String password;
private String valdUser;
private String isAdmin;
    /**
     * Creates new form AgentPage
     */
    public AgentPage(InfDB idb, String userName, String valdUser, String password, String isAdmin) {
        initComponents();
        this.idb = idb;
        this.userName = userName;
        this.valdUser = valdUser;
        this.password = password;
        this.isAdmin = isAdmin;
        btnAdminInlogg.setVisible(kollaIsAdmin(isAdmin));
        
    }
    
    // Helps to set btn visible or not
    // If isAdmin the button is visible and if not the button is hidden
    private boolean kollaIsAdmin(String isAdmin){
        if(isAdmin.equals("J")){
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        lblBild = new javax.swing.JLabel();
        btnBytLosen = new javax.swing.JButton();
        lblValkommenAgent = new javax.swing.JLabel();
        btnNyregistreraAlien = new javax.swing.JButton();
        btnAlienInfo = new javax.swing.JButton();
        btnRegistreraUtr = new javax.swing.JButton();
        btnAgentInfo = new javax.swing.JButton();
        btnAdminInlogg = new javax.swing.JButton();
        btnListaAlienPlats = new javax.swing.JButton();
        btnListaAlienRas = new javax.swing.JButton();
        btnListaAlienRas1 = new javax.swing.JButton();
        btnListaAlienRas2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiB Agenter.png"))); // NOI18N
        lblBild.setText("jLabel1");
        lblBild.setPreferredSize(new java.awt.Dimension(220, 326));

        btnBytLosen.setText("Byt Lösenord");
        btnBytLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytLosenActionPerformed(evt);
            }
        });

        lblValkommenAgent.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblValkommenAgent.setText("Välkommen Agent");

        btnNyregistreraAlien.setText("Registrera ny Alien");

        btnAlienInfo.setText("Sök Alien");
        btnAlienInfo.setToolTipText("");
        btnAlienInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlienInfoActionPerformed(evt);
            }
        });

        btnRegistreraUtr.setText("Registrera utrustning");

        btnAgentInfo.setText("Se vem som är områdeschef över visst område");
        btnAgentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentInfoActionPerformed(evt);
            }
        });

        btnAdminInlogg.setText("Administratör Inloggning");

        btnListaAlienPlats.setText("Lista Alien på plats");

        btnListaAlienRas.setText("Lista Alien på ras");

        btnListaAlienRas1.setText("Lista Alien registrerad MELLAN TVÅ datum");

        btnListaAlienRas2.setText("Ändra info om Alien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBild, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBytLosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdminInlogg)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNyregistreraAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAlienInfo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnRegistreraUtr)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(btnAgentInfo)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListaAlienRas1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListaAlienRas2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListaAlienRas, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListaAlienPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblValkommenAgent)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBild, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblValkommenAgent)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlienInfo)
                    .addComponent(btnRegistreraUtr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNyregistreraAlien)
                    .addComponent(btnAgentInfo))
                .addGap(18, 18, 18)
                .addComponent(btnListaAlienRas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListaAlienPlats)
                .addGap(18, 18, 18)
                .addComponent(btnListaAlienRas)
                .addGap(23, 23, 23)
                .addComponent(btnListaAlienRas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminInlogg)
                    .addComponent(btnBytLosen))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentInfoActionPerformed
        // TODO add your handling code here:
        new ChefOmrade(idb).setVisible(true);
    }//GEN-LAST:event_btnAgentInfoActionPerformed

    private void btnAlienInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlienInfoActionPerformed
        // TODO add your handling code here:
        new SokEnskildAlien(idb).setVisible(true);
    }//GEN-LAST:event_btnAlienInfoActionPerformed

    private void btnBytLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLosenActionPerformed
        // TODO add your handling code here:
        new AndraLosenord(idb, userName, valdUser, password).setVisible(true);
    }//GEN-LAST:event_btnBytLosenActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminInlogg;
    private javax.swing.JButton btnAgentInfo;
    private javax.swing.JButton btnAlienInfo;
    private javax.swing.JButton btnBytLosen;
    private javax.swing.JButton btnListaAlienPlats;
    private javax.swing.JButton btnListaAlienRas;
    private javax.swing.JButton btnListaAlienRas1;
    private javax.swing.JButton btnListaAlienRas2;
    private javax.swing.JButton btnNyregistreraAlien;
    private javax.swing.JButton btnRegistreraUtr;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblBild;
    private javax.swing.JLabel lblValkommenAgent;
    // End of variables declaration//GEN-END:variables
}
