
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author miche
 */
public class ChefOmrade extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form ChefOmrade
     */
    public ChefOmrade(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllValjOmrade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtaChefInfo = new javax.swing.JTextArea();
        cboxOmrade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtaChefInfo.setColumns(20);
        txtaChefInfo.setRows(5);
        jScrollPane1.setViewportView(txtaChefInfo);

        cboxOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj" }));
        cboxOmrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxOmradeActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cboxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(cboxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxOmradeActionPerformed
        // TODO add your handling code here:
        txtaChefInfo.setText("");
        ArrayList<HashMap<String, String>> soktaOmraden;

        try {

            String valtOmrade = cboxOmrade.getSelectedItem().toString();
            String sqlFraga = "SELECT agent.Agent_ID, agent.Namn FROM agent \n"
                    + "    JOIN omradeschef ON omradeschef.Agent_ID = agent.Agent_ID\n"
                    + "        JOIN omrade ON omrade.Omrades_ID=omradeschef.Agent_ID\n"
                    + "            WHERE omrade.Benamning= '" + valtOmrade + "'";

            soktaOmraden = idb.fetchRows(sqlFraga);

            if (soktaOmraden.size() < 1) {
                txtaChefInfo.append("Det finns ingen chef över detta område");
            }
            for (HashMap<String, String> ettOmrade : soktaOmraden) {
                txtaChefInfo.append(ettOmrade.get("Agent_ID") + "\t" + ettOmrade.get("Namn") + "\n");
//appendmetoden skriver in sträng i textrutan. Här läggs Hashmapen ettOmråde in som tar en key som inparameter. Här är key det som finns i selectsatsen i SQL frågan. 
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");

        }
    }//GEN-LAST:event_cboxOmradeActionPerformed

   private void fyllValjOmrade(){
        String fraga = "SELECT Benamning FROM omrade";

        ArrayList<String> allaOmraden;

        try {
            allaOmraden = idb.fetchColumn(fraga);

            for (String plats : allaOmraden) {
                cboxOmrade.addItem(plats);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxOmrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaChefInfo;
    // End of variables declaration//GEN-END:variables
}
