/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carolinaappel
 */
public class NULLAgentDatabasSokningar extends javax.swing.JFrame {

    /**
     * Creates new form AgentDatabasSokningar2
     */
    public NULLAgentDatabasSokningar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSokAndraAgent = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAdminStatus = new javax.swing.JButton();
        btnTaBortAgent = new javax.swing.JButton();
        btnAndraInfoAgent = new javax.swing.JButton();
        btnAndraOmradeschef = new javax.swing.JButton();
        btnAndraKontorschef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSokAndraAgent.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSokAndraAgent.setText("Sökningar och ändringar på Agenter");

        jButton1.setText("Sök info enskild agent");

        btnAdminStatus.setText("Ge annan Agent admin status");

        btnTaBortAgent.setText("Ta bort agent");

        btnAndraInfoAgent.setText("Ändra info om Agent");

        btnAndraOmradeschef.setText("Ändra områdeschef");

        btnAndraKontorschef.setText("Ändra kontorschef");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblSokAndraAgent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTaBortAgent)
                            .addComponent(btnAdminStatus)
                            .addComponent(btnAndraInfoAgent)
                            .addComponent(jButton1)
                            .addComponent(btnAndraOmradeschef)
                            .addComponent(btnAndraKontorschef))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblSokAndraAgent)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdminStatus)
                .addGap(18, 18, 18)
                .addComponent(btnTaBortAgent)
                .addGap(18, 18, 18)
                .addComponent(btnAndraInfoAgent)
                .addGap(18, 18, 18)
                .addComponent(btnAndraOmradeschef)
                .addGap(18, 18, 18)
                .addComponent(btnAndraKontorschef)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NULLAgentDatabasSokningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NULLAgentDatabasSokningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NULLAgentDatabasSokningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NULLAgentDatabasSokningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NULLAgentDatabasSokningar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminStatus;
    private javax.swing.JButton btnAndraInfoAgent;
    private javax.swing.JButton btnAndraKontorschef;
    private javax.swing.JButton btnAndraOmradeschef;
    private javax.swing.JButton btnTaBortAgent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblSokAndraAgent;
    // End of variables declaration//GEN-END:variables
}
