
import javax.swing.JOptionPane;
import oru.inf.InfException;
import oru.inf.InfDB;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author miche, aaau, cAppelina
 */
public class NyregistreraUtrustning extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form NyregistreraUtrustning
     */
    public NyregistreraUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
        //lblUtrustningsID.setText(getNextUtrustningsId());
        lblReg.setVisible(false);
        lblKategoriAttribut.setVisible(false);
        txtKategoriAttribut.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtBenamning = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        lblReg = new javax.swing.JLabel();
        cboxVäljKategori = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtKategoriAttribut = new javax.swing.JTextField();
        lblKategoriAttribut = new javax.swing.JLabel();

        jLabel2.setText("Välj kategori");

        jLabel3.setText("Benämning");

        btnReg.setText("Registrera");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        lblReg.setText("Utrustning registrerad");

        cboxVäljKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj", "Kommunikation", "Vapen", "Teknik" }));
        cboxVäljKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxVäljKategoriActionPerformed(evt);
            }
        });

        jLabel1.setText("Registrera ny utrustning");

        lblKategoriAttribut.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReg)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboxVäljKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblReg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKategoriAttribut)
                                    .addComponent(txtKategoriAttribut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboxVäljKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(lblKategoriAttribut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtKategoriAttribut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReg)
                    .addComponent(lblReg))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Lägger till ny utrustning
    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed

        String benamning = txtBenamning.getText();
        String kategori = cboxVäljKategori.getSelectedItem().toString();
        String kategoriAttribut = txtKategoriAttribut.getText();
        

        if (Validering.textFaltEjTomtRegEx(benamning) && Validering.kollaCboxRegEx(kategori)) {
            try {
                String nextId = getNextUtrustningsId();
                laggTillUtrustningIKategori(nextId,kategori, kategoriAttribut);
                
                String fraga = "INSERT INTO utrustning (Utrustnings_Id, Benamning) VALUES ( " + nextId + ", '" + benamning + "')";
                idb.insert(fraga);

                txtBenamning.setText("");
                lblReg.setVisible(true);
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Gick inte att registrera ny utrustning");
            }
        }
    }//GEN-LAST:event_btnRegActionPerformed

    private void cboxVäljKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxVäljKategoriActionPerformed
        // TODO add your handling code here:
        String kategori = cboxVäljKategori.getSelectedItem().toString();

        if (kategori.equalsIgnoreCase("kommunikation")) {
            lblKategoriAttribut.setText("Överföringsteknik");
            lblKategoriAttribut.setVisible(true);
            txtKategoriAttribut.setVisible(true);
            

        } else if (kategori.equalsIgnoreCase("Teknik")) {
            lblKategoriAttribut.setText("Kraftkälla");
            lblKategoriAttribut.setVisible(true);
            txtKategoriAttribut.setVisible(true);
        } else if (kategori.equalsIgnoreCase("vapen")) {
            lblKategoriAttribut.setText("Kaliber");
            lblKategoriAttribut.setVisible(true);
            txtKategoriAttribut.setVisible(true);
        }
    }//GEN-LAST:event_cboxVäljKategoriActionPerformed

    ////Kollar sista id som finns i tabellen och returnerar nästommande index
    private String getNextUtrustningsId() {
        String nextId = "";
        try {
            nextId = idb.getAutoIncrement("utrustning", "Utrustnings_ID");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Gick inte att hämta id för utrustning");
        }
        return nextId;
    }

    ///TEST!!!!!!!!!!!!!!
    //Kollar vilken ras som är vald som ny ras , anropar metoden för att 
    //ta bort den gamla rasen och lägger sedan till aliens id i den nya rasens tabell
    public void laggTillUtrustningIKategori(String utrustningsID, String kategori, String utrustningsAttribut) {

        
        if (kategori.equals("Kommunikation")) {
            try {
                String fraga = "INSERT INTO kommunikation (Utrustnings_ID,Overforingsteknik) VALUES (" + utrustningsID + ",'"+utrustningsAttribut+"')";
                idb.insert(fraga);
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Gick inte att lägga till utrustning");
            }
        } else if (kategori.equals("Vapen")) {
            try {
                String fraga = "INSERT INTO vapen (Utrustnings_ID, Kaliber) VALUES "
                        + "(" + utrustningsID + ",'" + utrustningsAttribut + "')";
                idb.insert(fraga);
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Gick inte att lägga till utrustning");
            }
        } else if (kategori.equals("Teknik")) {
            try {
                String fraga = "INSERT INTO teknik (Utrustnings_ID,Kraftkalla) VALUES "
                        + "(" + utrustningsID + ",'" + utrustningsAttribut + "')";
                idb.insert(fraga);
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Gick inte att lägga till utrustning");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReg;
    private javax.swing.JComboBox<String> cboxVäljKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblKategoriAttribut;
    private javax.swing.JLabel lblReg;
    private javax.swing.JTextField txtBenamning;
    private javax.swing.JTextField txtKategoriAttribut;
    // End of variables declaration//GEN-END:variables
}
