
import javax.swing.JOptionPane;
import oru.inf.InfException;
import oru.inf.InfDB;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author miche
 */
public class NyregistreraUtrustning extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form NyregistreraUtrustning
     */
    public NyregistreraUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
        lblUtrustningsID.setText(getUtrustningsId());
        lblReg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUtrustningsID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBenamning = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        lblReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUtrustningsID.setText("jLabel1");

        jLabel2.setText("Utrustnings ID");

        jLabel3.setText("Benämning");

        btnReg.setText("Registrera");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        lblReg.setText("Utrustning registrerad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReg)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(29, 29, 29)
                            .addComponent(lblUtrustningsID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))))
                .addGap(18, 18, 18)
                .addComponent(lblReg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtrustningsID)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReg)
                    .addComponent(lblReg))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        String benamning = txtBenamning.getText();
        
        if(Validering.textFaltHarVarde(txtBenamning)){
          try{
              String nextId = getUtrustningsId();
              String fraga = "INSERT INTO utrustning (Utrustnings_Id, Benamning) VALUES ( "+ nextId +", '"+ benamning +"')";
              idb.insert(fraga);
              
              txtBenamning.setText("");
              lblReg.setVisible(true);
          }
          catch(InfException ex){
                JOptionPane.showMessageDialog(null, "Gick inte att registrera ny utrustning");
            }
        }
    }//GEN-LAST:event_btnRegActionPerformed
     private String getUtrustningsId(){
        String nextId = "";
        try{
            nextId = idb.getAutoIncrement("utrustning","Utrustnings_ID");
        }
        catch(InfException ex){
                JOptionPane.showMessageDialog(null, "Gick inte att hämta id för utrustning");
        }
        return nextId;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblUtrustningsID;
    private javax.swing.JTextField txtBenamning;
    // End of variables declaration//GEN-END:variables
}
