
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author miche, aaau, cAppelina
 */
public class SokEnskildAgent extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Skapar ny SokEnskildAgent
     */
    public SokEnskildAgent(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSokInfoAgent = new javax.swing.JLabel();
        txtNamnSok = new javax.swing.JTextField();
        btnSok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaAgentInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        lblSokInfoAgent.setText("Sök info om agent");

        txtNamnSok.setColumns(5);

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        txtaAgentInfo.setColumns(40);
        txtaAgentInfo.setRows(5);
        jScrollPane1.setViewportView(txtaAgentInfo);

        jLabel1.setText("Skriv in agentens namn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNamnSok)
                            .addComponent(btnSok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblSokInfoAgent)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblSokInfoAgent)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamnSok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(btnSok)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed

        txtaAgentInfo.setText("");
        String soktNamn = txtNamnSok.getText();
        //boolean inmatningOk = Validering.textFaltEjTomtRegEx(soktNamn);
        //if (!inmatningOk) {
            //txtNamnSok.requestFocus();
       // }

       
        ArrayList<HashMap<String, String>> soktaNamn;
        if(Validering.textFaltEjTomtRegEx(soktNamn))
        try {

            String fraga = "SELECT agent.Agent_ID, agent.Namn, agent.Telefon, agent.Administrator, \n"
                    + "omrade.Benamning FROM agent \n"
                    + "JOIN omrade ON omrade.Omrades_ID = agent.Omrade \n"
                    + " WHERE agent.Namn = '" + soktNamn + "'";

            soktaNamn = idb.fetchRows(fraga);
            
            txtaAgentInfo.append("AgentID" + "\t" + "Agentnamn" + "\t" + "telefonnr" + "\t"
                    + "Admin J/N" + "\t" + "Område" + "\n");
             if (soktaNamn.size() < 1) {
                    txtaAgentInfo.setText("Det finns ingen agent med detta namn, försök igen!");
                }
            for (HashMap<String, String> ettNamn : soktaNamn) {
                txtaAgentInfo.append(ettNamn.get("Agent_ID") + "\t" + ettNamn.get("Namn") + "\t" + ettNamn.get("Telefon") 
                        + "\t" + ettNamn.get("Administrator") + "\t" + ettNamn.get("Benamning"));
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel vid databaskopplingen \n" + e.getMessage());
                System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnSokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSokInfoAgent;
    private javax.swing.JTextField txtNamnSok;
    private javax.swing.JTextArea txtaAgentInfo;
    // End of variables declaration//GEN-END:variables
}
