
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carolinaappel
 * Experimenterar. Har använt textfält och lagrar valet från comboboxen, men ej skrivit klar SQL frågan för att ta bort
 * utrustningen.
 */
public class TaBortUtrustning extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form TaBortUtrustning
     */
    public TaBortUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllValjUtrustning();
        lblBorttagenUtrustning.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUtrustning = new javax.swing.JComboBox<>();
        lblRubrik = new javax.swing.JLabel();
        cbxTaBort = new javax.swing.JCheckBox();
        lblBorttagenUtrustning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbUtrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj" }));
        cmbUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUtrustningActionPerformed(evt);
            }
        });

        lblRubrik.setText("Välj utrusting");

        cbxTaBort.setText("Ta bort vald utrustning");
        cbxTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTaBortActionPerformed(evt);
            }
        });

        lblBorttagenUtrustning.setText("Utrustningen har tagits bort");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBorttagenUtrustning)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(cbxTaBort))
                    .addComponent(lblRubrik))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTaBort))
                .addGap(31, 31, 31)
                .addComponent(lblBorttagenUtrustning)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUtrustningActionPerformed
        // metoden används inte men jag har inte tid att klura ut varför jag inte kan ta bort den.
        
        
       /* ArrayList<HashMap<String, String>> soktUtrustning;
        
        try{
            String valdUtrustning = cmbUtrustning.getSelectedItem().toString();
            String sqlFraga = "SELECT utrustning.Utrustnings_ID, utrustning.Benamning FROM Utrustning \n"
                    + "    WHERE utrustning.Benamning= '" + valdUtrustning + "'";
        
            soktUtrustning = idb.fetchRows(sqlFraga);
            
            for (HashMap<String, String> enUtrustning : soktUtrustning) {
                txtaValdUtrustning.append(enUtrustning.get("Utrustnings_ID") + "\t" + enUtrustning.get("Benamning") + "\n");
            
        }
        }
        catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        
        } */ 
    }//GEN-LAST:event_cmbUtrustningActionPerformed

    private void cbxTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTaBortActionPerformed
        // OBS! Va försiktig med att klicka i rutan då data tas bort från tabell 
        String utrustningNamn = cmbUtrustning.getSelectedItem().toString();
        
        String fraga = "DELETE FROM Utrustning WHERE Benamning =" + "'" + utrustningNamn + "'" + ";";
        
        try {
            idb.delete(fraga);
            lblBorttagenUtrustning.setVisible(true);
            System.out.println("funkar");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }//GEN-LAST:event_cbxTaBortActionPerformed

    private void fyllValjUtrustning(){
    
        String fraga = "SELECT Benamning FROM Utrustning";
    
        ArrayList<String> allUtrustning;
        
        try
        {
            allUtrustning = idb.fetchColumn(fraga);

            for (String plats : allUtrustning) {
                cmbUtrustning.addItem(plats);
            }
        }
        catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxTaBort;
    private javax.swing.JComboBox<String> cmbUtrustning;
    private javax.swing.JLabel lblBorttagenUtrustning;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
