
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carolinaappel
 * experimenterar. Måste lösa hur valet i comboboxen ska lagras för att kunna tas bort.
 */
public class TaBortAgent extends javax.swing.JFrame {
    private InfDB idb;
    private HjalpDbFunktioner konv;
    /**
     * Creates new form TaBortAgent
     */
    public TaBortAgent(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllValjAgent();
        lblBorttagenAgent.setVisible(false);
        konv = new HjalpDbFunktioner(idb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        cmbAgenter = new javax.swing.JComboBox<>();
        lblBorttagenAgent = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setText("Välj Agent att ta bort");

        cmbAgenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj" }));

        lblBorttagenAgent.setText("Agenten har tagits bort");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaBort))
                        .addGap(18, 18, 18)
                        .addComponent(lblBorttagenAgent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblRubrik)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblRubrik)
                .addGap(18, 18, 18)
                .addComponent(cmbAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBorttagenAgent)
                    .addComponent(btnTaBort))
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        String namn = cmbAgenter.getSelectedItem().toString();
        String agentId = konv.faUtAgentID(namn);
        
        if(Validering.kollaTaBort(namn)){
            String fragaAgent = "DELETE FROM Agent WHERE Agent_ID ='" + agentId + "'";
            String fragaFaltAgent = "DELETE FROM Agent WHERE Agent_ID ='" + agentId + "'";
            String fragaKontChef = "DELETE FROM Agent WHERE Agent_ID ='" + agentId + "'";
            String fragaOmrChef = "DELETE FROM Agent WHERE Agent_ID ='" + agentId + "'";
            try {
                idb.delete(fragaAgent);
                idb.delete(fragaFaltAgent);
                idb.delete(fragaKontChef);
                idb.delete(fragaOmrChef);
                
                lblBorttagenAgent.setVisible(true);
                lblBorttagenAgent.setText(namn + "är borttagen ur systemet");
            }
           catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Gick inte att ta bort");
            }
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void fyllValjAgent(){
        String fraga = "SELECT Namn FROM Agent";
        
        ArrayList<String> allaAgenter; 
        
        try {
            allaAgenter = idb.fetchColumn(fraga);

            for (String plats : allaAgenter) {
                cmbAgenter.addItem(plats);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Gick ej att ladda agenter");
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> cmbAgenter;
    private javax.swing.JLabel lblBorttagenAgent;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}



/* skräp:
try{
            String soktNamn = cmbAgenter.getName();
            String agentFraga = "SELECT Namn FROM Agent WHERE Agent.namn = '" + soktNamn + "'";
            String svar = idb.fetchSingle(agentFraga);
            lblValdAgent.setText(svar);
            
            if(svar == null) {
                System.out.println("Agent hittades inte");
                JOptionPane.showMessageDialog(null, "Agent hittades inte, skriv in rätt Agentnamn"); 
            }
            
        }
        catch(InfException e){
            System.out.println("Något gick fel");
            JOptionPane.showMessageDialog(null, "Något gick fel");  
    }
*/

 // OBS! Va försiktig med att klicka i rutan då data tas bort från tabell
       /* String namn = cmbAgenter.getSelectedItem().toString();
        if(Validering.kollaTaBort(namn)){
            String fraga = "DELETE FROM Agent WHERE Namn =" + "'" + namn + "'" + ";";
            try {
                idb.delete(fraga);
                
                lblBorttagenAgent.setVisible(true);
                lblBorttagenAgent.setText(namn + "är borttagen ur systemet");
            }
           catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Gick inte att ta bort");
            }
        }*/